"""RSA host keys whose arithmetic is wrong.

This is the shape of check the policy file cannot express. Everything there
matches: a name, a version window, a directive's value. Nothing there can
divide a number.

Three faults are looked for, all of which mean the private key is recoverable
or the signatures are forgeable, and none of which show up as a weak algorithm
name -- the key is a perfectly ordinary ``rsa-sha2-512`` of a perfectly
ordinary size:

* a modulus with a small prime factor, which happens when a key is generated
  on a host with no entropy and means the key can be factored outright;
* a public exponent of 1 or an even one, which is not a valid RSA key at all
  and indicates a broken generator;
* a public exponent of 3, which is legal and fast and has a long history of
  implementation mistakes around padding.

Trial division stops early on purpose. It is not trying to factor real keys;
it is catching the ones a broken generator produced, whose factors are tiny.
"""

from typing import Any

from ssh_crypto_checker.plugins import Detected

ID = "RSA-KEY-QUALITY"
NAME = "RSA host key with unsound parameters"
SEVERITY = "critical"
DESCRIPTION = (
    "The server's RSA host key fails an arithmetic check. A key like this is not weak in "
    "the sense of being short; it is wrong, and whoever notices can impersonate the server."
)
REMEDIATION = (
    "Generate a new host key on a machine with working entropy "
    "('ssh-keygen -t ed25519' is the better answer), point HostKey at it, restart sshd and "
    "update the clients' known_hosts. Treat the old key as compromised."
)
REFERENCES = [
    "https://factorable.net/",
    "CVE-2008-0166",
]
NEEDS = ["host_keys"]

#: Every prime below 1000. A modulus divisible by one of these was not
#: generated by anything that works, and finding it costs microseconds.
_SMALL_PRIMES = [
    p
    for p in range(2, 1000)
    if all(p % factor for factor in range(2, int(p**0.5) + 1))
]


def check(server: Any) -> Any:
    faults = []
    for key in server.host_keys:
        if getattr(key, "error", None) is not None:
            continue
        if (getattr(key, "key_family", "") or "").lower() != "rsa":
            continue

        modulus = getattr(key, "modulus", None)
        exponent = getattr(key, "public_exponent", None)
        label = f"{key.algorithm} {key.fingerprint_sha256}"

        if exponent is not None:
            if exponent < 3 or exponent % 2 == 0:
                faults.append(f"{label}: public exponent {exponent} is not a valid RSA exponent")
            elif exponent == 3:
                faults.append(
                    f"{label}: public exponent 3, which is legal but has a long history of "
                    "padding mistakes"
                )

        if modulus is not None:
            if modulus <= 0:
                # RFC 4251 mpints are signed, and a positive number whose top
                # bit is set has to carry a leading zero byte. An implementation
                # that omits it sends what reads as a negative modulus -- and a
                # negative modulus is not a key: no client can verify a
                # signature against it. Reporting the bit length and nothing
                # else would describe an unusable key as a healthy one.
                faults.append(
                    f"{label}: modulus is not a positive number, so this is not a usable "
                    "RSA key; the encoding is most likely missing its leading zero byte"
                )
            else:
                for prime in _SMALL_PRIMES:
                    if modulus % prime == 0:
                        faults.append(
                            f"{label}: modulus is divisible by {prime}, so the key can be "
                            "factored"
                        )
                        break

    if not faults:
        return None
    # A tiny factor means the key is recoverable now; exponent 3 alone is a
    # smell rather than a break, so it is not reported at the same severity.
    factored = any(
        "factored" in fault or "not a valid" in fault or "not a positive" in fault
        for fault in faults
    )
    return Detected(evidence=faults, severity=None if factored else "low")
